#!/usr/bin/env python3
import logging
import sys
import asyncio

from helperlib.logging import default_config, load_config

from ctfpwn.db import CtfDb
from ctfpwn.shared import load_ctf_config
from ctfpwn.exploitservice.supervisor import Supervisor

log = logging.getLogger(__name__)


async def stats(db, config):
    while True:
        await db.exploit_stats()
        await asyncio.sleep(config.get('exploit_stats_interval'))

async def _start(loop, config):
    db = await CtfDb.create(config=config)
    loop.create_task(stats(db, config))
    supervisor = Supervisor(db, config)
    supervisor.start(config.get('exploit_supervisor_interval'))

def run_exploitservice():
    try:
        load_config('exploitservice.ini', disable_existing_loggers=False)
    except Exception as e:
        default_config(level=logging.DEBUG, disable_existing_loggers=False)
        log.warning('No logging config file exploitservice.ini found. Using default')

    config = load_ctf_config('config.yaml')
    log.info('Starting Exploit Service')
    loop = asyncio.get_event_loop()
    loop.create_task(_start(loop, config))
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        tasks = asyncio.Task.all_tasks()
        log.warning("Caught keyboard interrupt. Canceling %d tasks...", len(tasks))
        tasks = asyncio.gather(*tasks)
        tasks.cancel()
        loop.stop()
        loop.run_forever()
        # tasks.exception()
    except Exception as e:
        print(e)
        sys.exit(1)
    finally:
        loop.close()

if __name__ == '__main__':
    run_exploitservice()
